import { expect, test, type Locator, type Page } from '@playwright/test'

async function login(page: Page, username = 'admin', password = 'admin123') {
  await page.goto('/login')
  await page.getByLabel('用户名').fill(username)
  await page.getByLabel('密码').fill(password)
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '工作台' })).toBeVisible()
}

async function selectByText(locator: Locator, text: string) {
  const value = await locator.locator('option').filter({ hasText: text }).first().getAttribute('value')
  if (!value) throw new Error(`下拉选项不存在：${text}`)
  await locator.selectOption(value)
}

async function chooseAutocomplete(page: Page, label: string, text: string) {
  const box = page.locator('label.item-combobox').filter({ hasText: label }).first()
  await box.locator('input').fill(text)
  const option = box.getByRole('option').filter({ hasText: text }).first()
  const more = box.getByRole('button', { name: '继续加载剩余物料', exact: true })
  await expect.poll(async () =>
    (await box.locator('input').inputValue()).includes('｜')
    || await option.isVisible().catch(() => false)
    || await more.isVisible().catch(() => false),
  ).toBe(true)
  for (let attempt = 0; attempt < 6; attempt += 1) {
    if (await option.isVisible().catch(() => false)) { await option.click(); break }
    if ((await box.locator('input').inputValue()).includes('｜')) break
    if (!(await more.isVisible().catch(() => false))) break
    const response = page.waitForResponse(result => result.ok() && result.url().includes('/api/items?limit=1000&offset='))
    await more.click()
    await response
  }
  await expect(box.locator('input')).toHaveValue(new RegExp(`${text.replaceAll('.', '\\.')}.+`))
}

async function expectSelectedListRow(page: Page, code: string) {
  const row = page.getByTestId('item-list-table').locator(`tr[data-item-code="${code}"]`)
  const scroller = page.getByTestId('item-list-scroll')
  await expect(row).toHaveCount(1)
  await expect(row).toHaveClass(/selected-row/)
  await expect(row).toHaveAttribute('aria-selected', 'true')
  await expect.poll(async () => {
    const rowBox = await row.boundingBox(); const scrollBox = await scroller.boundingBox()
    return !!rowBox && !!scrollBox && rowBox.y >= scrollBox.y - 1 && rowBox.y + rowBox.height <= scrollBox.y + scrollBox.height + 1
  }).toBe(true)
}

test.describe('BOM V1 全功能验收', () => {
  test('登录校验与全部导航页面可达', async ({ page }) => {
    await page.goto('/login')
    await page.getByLabel('密码').fill('wrong-password')
    await page.getByRole('button', { name: '登录', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('用户名或密码错误')
    await page.getByLabel('密码').fill('admin123')
    await page.getByRole('button', { name: '登录', exact: true }).click()
    await expect(page.getByRole('heading', { name: '工作台' })).toBeVisible()

    const pages: [string, string][] = [
      ['原材料', '原材料管理'], ['半成品', '半成品管理'], ['单元', '单元管理'], ['整机', '整机管理'],
      ['物料导入', '物料 Excel 导入'], ['批量维护', 'BOM 批量维护'], ['BOM 比较', 'BOM 矩阵比较'],
      ['选配替代', '选配关系总览'], ['编码规则', '编码规则'], ['变更日志', '变更日志'], ['账户管理', '账户管理'],
    ]
    for (const [link, heading] of pages) {
      await page.getByRole('link', { name: link, exact: true }).click()
      await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
    }
    const materialPages: [string, string][] = [
      ['原材料', '90.9001.01'], ['半成品', '05.999.01'], ['单元', '03.999.01'], ['整机', '00.999.01'],
    ]
    for (const [link, code] of materialPages) {
      await page.getByRole('link', { name: link, exact: true }).click()
      await expect(page.getByRole('button', { name: '查询', exact: true })).toHaveCount(0)
      await chooseAutocomplete(page, '搜索物料', code)
      await expect(page.getByRole('heading', { name: code, exact: true })).toBeVisible()
      await expectSelectedListRow(page, code)
    }
  })

  test('四类物料页面左右栏可拖动调整并记忆宽度', async ({ page }) => {
    await page.setViewportSize({ width: 1600, height: 900 })
    await login(page)
    await page.getByRole('link', { name: '原材料', exact: true }).click()
    const loadPanel = page.getByTestId('item-list-load-more')
    await expect(loadPanel).toContainText(/已加载 1000 \/ \d+ 条/)
    await loadPanel.getByRole('button', { name: '继续加载下一批' }).click()
    await expect(loadPanel).toContainText(/已加载 2000 \/ \d+ 条/)
    await expect(page.getByTestId('item-list-table').locator('tbody tr')).toHaveCount(2000)
    await expect(page.getByTestId('item-list-table').locator('tr[data-item-code="15.1017.0"]')).toHaveCount(1)
    const searchBox = page.locator('label.item-combobox').filter({ hasText: '搜索物料' }).first()
    const prefixSearch = page.waitForResponse(response => response.ok() && response.url().includes('/api/items?') && response.url().includes('q=17.'))
    await searchBox.locator('input').fill('17.')
    const prefixResult = await prefixSearch
    expect((await prefixResult.json()).total).toBeGreaterThan(0)
    await expect(searchBox.getByRole('option').first()).toContainText(/^17\./)
    await expect(searchBox.getByText(/全库匹配 \d+ 条/)).toBeVisible()
    await expect(searchBox.getByRole('button', { name: '继续加载剩余物料', exact: true })).toHaveCount(0)
    await searchBox.getByRole('option').first().click()
    await expectSelectedListRow(page, await searchBox.locator('input').inputValue().then(value => value.split('｜')[0]))
    await searchBox.locator('input').fill('')
    await expect(searchBox.getByRole('button', { name: '继续加载剩余物料', exact: true })).toBeVisible()
    const nextFilteredPage = page.waitForResponse(response => {
      const url = new URL(response.url())
      return response.ok() && url.pathname === '/api/items' && url.searchParams.get('item_type') === 'material'
        && url.searchParams.get('offset') === '2000'
    })
    await searchBox.getByRole('button', { name: '继续加载剩余物料', exact: true }).click()
    await nextFilteredPage
    await expect(searchBox.getByText(/浏览数据 3\d{3} \/ \d+ 条/)).toBeVisible()
    const separator = page.getByRole('separator', { name: '调整物料列表和详情栏宽度' })
    const listPane = page.locator('.resizable-split > section').first()
    await expect(separator).toBeVisible()
    const before = await listPane.boundingBox()
    const handle = await separator.boundingBox()
    if (!before || !handle) throw new Error('无法读取可调栏宽布局')
    await page.mouse.move(handle.x + handle.width / 2, handle.y + 80)
    await page.mouse.down()
    await page.mouse.move(handle.x + handle.width / 2 + 140, handle.y + 80, { steps: 8 })
    await page.mouse.up()
    await expect.poll(async () => (await listPane.boundingBox())?.width || 0).toBeGreaterThan(before.width + 100)
    const resizedWidth = (await listPane.boundingBox())?.width || 0
    await page.reload()
    await expect(page.getByRole('separator', { name: '调整物料列表和详情栏宽度' })).toBeVisible()
    await expect.poll(async () => (await page.locator('.resizable-split > section').first().boundingBox())?.width || 0).toBeGreaterThan(resizedWidth - 3)
    for (const link of ['半成品', '单元', '整机']) {
      await page.getByRole('link', { name: link, exact: true }).click()
      await expect(page.getByRole('separator', { name: '调整物料列表和详情栏宽度' })).toBeVisible()
      await expect(page.getByTestId('item-list-load-more')).toContainText('已显示全部')
    }
  })

  test('原材料来源与产品状态按全库筛选，并支持全选反选', async ({ page }) => {
    await login(page)
    await page.getByRole('link', { name: '原材料', exact: true }).click()
    const materialFilter = page.locator('select[aria-label="原材料来源筛选"]')
    const materialCases: [string, string][] = [
      ['purchased', '外购'], ['outsourced', '外协'], ['self_made', '自制'],
    ]
    for (const [value, label] of materialCases) {
      const responsePromise = page.waitForResponse(response => {
        const url = new URL(response.url())
        return response.ok() && url.pathname === '/api/items' && url.searchParams.get('item_type') === 'material'
          && url.searchParams.get('source_type') === value && !url.searchParams.has('q')
      })
      await materialFilter.selectOption(value)
      const payload = await (await responsePromise).json()
      await expect(page.getByText(`当前筛选已加载 ${payload.items.length} / ${payload.total} 条`, { exact: true })).toBeVisible()
      await expect(page.getByTestId('item-list-table').locator('tbody tr')).toHaveCount(payload.items.length)
      const labels = await page.getByTestId('item-list-table').locator('tbody tr td:last-child .tag').allTextContents()
      expect(labels.every(text => text.trim() === label)).toBe(true)
    }

    const productCases: [string, string][] = [
      ['半成品', 'semi_finished'], ['单元', 'unit'], ['整机', 'machine'],
    ]
    const statusCases: [string, string][] = [
      ['trial', '试制'], ['active', '在用'], ['disabled', '停用'],
    ]
    for (const [link, itemType] of productCases) {
      await page.getByRole('link', { name: link, exact: true }).click()
      const statusFilter = page.locator('select[aria-label="物料状态筛选"]')
      for (const [value, label] of statusCases) {
        const responsePromise = page.waitForResponse(response => {
          const url = new URL(response.url())
          return response.ok() && url.pathname === '/api/items' && url.searchParams.get('item_type') === itemType
            && url.searchParams.get('status') === value && !url.searchParams.has('q')
        })
        await statusFilter.selectOption(value)
        const payload = await (await responsePromise).json()
        await expect(page.getByText(`当前筛选已加载 ${payload.items.length} / ${payload.total} 条`, { exact: true })).toBeVisible()
        await expect(page.getByTestId('item-list-table').locator('tbody tr')).toHaveCount(payload.items.length)
        const labels = await page.getByTestId('item-list-table').locator('tbody tr td:last-child .tag').allTextContents()
        expect(labels.every(text => text.trim() === label)).toBe(true)
      }

      const trialResponse = page.waitForResponse(response => {
        const url = new URL(response.url())
        return response.ok() && url.pathname === '/api/items' && url.searchParams.get('item_type') === itemType
          && url.searchParams.get('status') === 'trial' && !url.searchParams.has('q')
      })
      await statusFilter.selectOption('trial')
      const trialPayload = await (await trialResponse).json()
      await expect(page.getByText(`当前筛选已加载 ${trialPayload.items.length} / ${trialPayload.total} 条`, { exact: true })).toBeVisible()
      await page.getByRole('button', { name: '全选筛选结果', exact: true }).click()
      await expect(page.getByText(`已选 ${trialPayload.total} 项`, { exact: true })).toBeVisible()
      await page.getByRole('button', { name: '反选当前页', exact: true }).click()
      await expect(page.getByText('已选 0 项', { exact: true })).toBeVisible()
    }
  })

  test('整机按名称归类机型并可筛选', async ({ page }) => {
    await login(page)
    await page.getByRole('link', { name: '整机', exact: true }).click()
    const modelFilter = page.getByLabel('整机机型筛选')
    await expect(modelFilter.locator('option')).toHaveText([
      '全部机型', 'D60', 'G65', 'J60B', 'R60', 'T60', 'T65', 'T70', 'Y60', '其他机型',
    ])
    const responsePromise = page.waitForResponse(response => {
      const url = new URL(response.url())
      return response.ok() && url.pathname === '/api/items'
        && url.searchParams.get('item_type') === 'machine'
        && url.searchParams.get('machine_model') === 'D60'
        && !url.searchParams.has('q')
    })
    await modelFilter.selectOption('D60')
    const payload = await (await responsePromise).json()
    expect(payload.total).toBeGreaterThan(0)
    await expect(page.getByText(`当前筛选已加载 ${payload.items.length} / ${payload.total} 条`, { exact: true })).toBeVisible()
    expect(payload.items.every((item: { machine_model?: string }) => item.machine_model === 'D60')).toBe(true)
  })

  test('物料创建、逐级编码引导、BOM 编辑、展开、导出与复制版本', async ({ page }) => {
    test.setTimeout(300_000)
    await login(page)
    await page.getByRole('link', { name: '原材料', exact: true }).click()
    await page.getByTestId('new-item').click()
    await expect(page.getByLabel('大类').locator('option').nth(1)).toContainText('钣金件、机柜、站房及其配件 | 10')
    await page.getByLabel('大类').selectOption({ index: 1 })
    await expect(page.getByLabel('小类').locator('option').nth(1)).toContainText('仪器机柜 | 10.1')
    await page.getByLabel('小类').selectOption({ index: 1 })
    await page.getByLabel('编码规则').selectOption({ index: 1 })
    await expect(page.getByTestId('code-rule-prefix')).toHaveText('10.1')
    await expect(page.getByLabel('系统物料编码后缀')).not.toHaveValue('')
    await page.getByLabel('系统物料编码后缀').fill('10.01')
    await expect(page.getByTestId('full-material-code')).toHaveText('10.110.01')
    await expect(page.getByText(/系统物料编码必须符合所选规则/)).toBeVisible()
    await expect(page.getByRole('button', { name: '创建物料' })).toBeDisabled()
    await page.getByLabel('编码规则').selectOption('0')
    await page.getByLabel('系统物料编码').fill('01.9901.01')
    await page.getByLabel('名称', { exact: true }).fill('E2E基础原材料')
    await page.getByLabel('规格型号').fill('E2E-MAT-01')
    await page.getByText('已检查并确认可能存在的高度相似物料').click()
    await page.getByRole('button', { name: '创建物料' }).click()
    await expect(page.getByText('物料创建成功')).toBeVisible()
    page.once('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: '删除', exact: true }).click()
    await expect(page.getByRole('row', { name: /01\\.9901\\.01 E2E基础原材料/ })).toHaveCount(0)
    await page.getByTestId('new-item').click()
    await page.getByLabel('系统物料编码').fill('01.9901.01')
    await page.getByLabel('名称', { exact: true }).fill('E2E基础原材料')
    await page.getByLabel('规格型号').fill('E2E-MAT-01')
    await page.getByText('已检查并确认可能存在的高度相似物料').click()
    await page.getByRole('button', { name: '创建物料' }).click()
    await expect(page.getByText('物料创建成功')).toBeVisible()

    await page.getByTestId('new-item').click()
    const createModal = page.locator('.modal')
    await createModal.getByLabel('系统物料编码').fill('01.9901.01')
    await expect(createModal.getByText('系统物料编码已存在')).toBeVisible()
    await expect(createModal.getByText(/当前系列最大已存在：/)).toBeVisible()
    await expect(createModal.getByRole('button', { name: '使用同主体下一版本 01.9901.02' })).toBeVisible()
    await expect(createModal.getByRole('button', { name: /使用下一主体/ })).toBeVisible()
    await expect(createModal.getByRole('button', { name: '创建物料' })).toBeDisabled()

    await chooseAutocomplete(page, '选择要复制的原材料', '10.1001.0')
    await createModal.getByRole('button', { name: '复制并自动填充' }).click()
    await expect(createModal.getByLabel('大类')).toHaveValue('钣金件、机柜、站房及其配件')
    await expect(createModal.getByLabel('小类')).toHaveValue('仪器机柜')
    await expect(createModal.getByLabel('编码规则').locator('option:checked')).toContainText('机柜,钣金件')

    const copyInput = createModal.locator('label.item-combobox').filter({ hasText: '选择要复制的原材料' }).locator('input')
    await copyInput.focus()
    await copyInput.press('Control+A')
    await copyInput.press('Backspace')
    await expect(copyInput).toHaveValue('')
    await expect(createModal).toBeVisible()
    await expect(createModal.locator('label.item-combobox').filter({ hasText: '选择要复制的原材料' }).getByRole('option').first()).toBeVisible()
    await chooseAutocomplete(page, '选择要复制的原材料', '10.1002.0')
    await createModal.getByRole('button', { name: '清除选择要复制的原材料' }).click()
    await expect(copyInput).toHaveValue('')
    await expect(createModal).toBeVisible()

    await chooseAutocomplete(page, '选择要复制的原材料', '90.9003.01')
    await createModal.getByRole('button', { name: '复制并自动填充' }).click()
    await expect(createModal.getByLabel('系统物料编码')).toHaveValue('90.9003.02')
    await expect(createModal.getByLabel('来源')).toHaveValue('self_made')
    await expect(createModal.getByLabel('大类')).toHaveValue('')
    await expect(createModal.getByLabel('小类')).toHaveValue('')
    await expect(createModal.getByLabel('编码规则')).toHaveValue('0')
    await expect(createModal.getByText(/90\.9002\.01 演示-水质采集电路板 × 1/)).toBeVisible()
    await expect(createModal.getByText(/90\.9001\.01 演示-M4不锈钢螺钉 × 4/)).toBeVisible()

    await chooseAutocomplete(page, '选择要复制的原材料', '01.9901.01')
    await createModal.getByRole('button', { name: '复制并自动填充' }).click()
    await expect(createModal.getByLabel('系统物料编码')).toHaveValue('01.9901.02')
    await expect(createModal.getByLabel('名称', { exact: true })).toHaveValue('E2E基础原材料')
    await expect(createModal.getByLabel('规格型号')).toHaveValue('E2E-MAT-01')
    await expect(createModal.getByLabel('上一版本名称')).toHaveValue('E2E基础原材料')
    await expect(createModal.getByText('系统物料编码可用')).toBeVisible()
    await createModal.getByRole('button', { name: '创建物料' }).click()
    await expect(page.getByText('物料创建成功')).toBeVisible()
    await expect(page.getByRole('heading', { name: '01.9901.02', exact: true })).toBeVisible()

    await page.getByRole('link', { name: '半成品', exact: true }).click()
    await page.getByTestId('new-item').click()
    await page.getByLabel('系统物料编码').fill('01.9902.01')
    await page.getByLabel('名称', { exact: true }).fill('E2E测试半成品')
    await page.getByText('已检查并确认可能存在的高度相似物料').click()
    await page.getByRole('button', { name: '创建物料' }).click()
    await expect(page.getByText('物料创建成功')).toBeVisible()
    await page.getByRole('button', { name: 'BOM 编辑' }).click()
    const childSearch = page.locator('label.item-combobox').filter({ hasText: '搜索子物料' })
    const childPrefixSearch = page.waitForResponse(response => response.ok() && response.url().includes('/api/items?') && response.url().includes('q=10.'))
    await childSearch.locator('input').fill('10.')
    await childPrefixSearch
    await expect(childSearch.getByRole('option').first()).toContainText(/^10\./)
    await expect(childSearch.getByText(/匹配 \d+ 条/)).toBeVisible()
    await expect(childSearch.getByRole('button', { name: '继续加载剩余物料', exact: true })).toHaveCount(0)
    await chooseAutocomplete(page, '搜索子物料', '01.9901.01')
    await page.getByLabel('BOM数量').fill('2.5')
    await page.getByRole('button', { name: '添加组成' }).click()
    await expect(page.getByText(/BOM 组成已添加.*已刷新/)).toBeVisible()
    const directRow = page.getByTestId('direct-bom-table').getByRole('row', { name: /01\.9901\.01/ })
    await expect(directRow).toContainText('E2E基础原材料')
    await directRow.getByLabel('01.9901.01 数量').fill('3.75')
    await directRow.getByRole('button', { name: '保存数量' }).click()
    await expect(page.getByText(/01\.9901\.01 的数量已保存.*已刷新/)).toBeVisible()
    await expect(directRow.getByLabel('01.9901.01 数量')).toHaveValue('3.750000')

    await directRow.getByRole('button', { name: '快速查看 01.9901.01', exact: true }).click()
    const quickView = page.getByRole('dialog', { name: '快速查看物料 01.9901.01' })
    await expect(quickView).toBeVisible()
    await expect(quickView).toContainText('E2E基础原材料')
    await expect(quickView).toContainText('E2E-MAT-01')
    await expect(quickView.getByRole('heading', { name: '直接组成' })).toHaveCount(0)
    await expect(page.getByRole('heading', { name: '01.9902.01', exact: true })).toBeVisible()
    const fullItemPagePromise = page.context().waitForEvent('page')
    await quickView.getByRole('link', { name: '在新标签页打开完整界面' }).click()
    const fullItemPage = await fullItemPagePromise
    await fullItemPage.waitForLoadState('domcontentloaded')
    await expect(fullItemPage.getByRole('heading', { name: '01.9901.01' })).toBeVisible()
    await expect(fullItemPage.getByTestId('item-detail').getByLabel('变更说明')).toHaveCount(0)
    await fullItemPage.getByLabel('名称', { exact: true }).fill('E2E基础原材料-已修改')
    await fullItemPage.getByLabel('规格型号').fill('E2E-MAT-02')
    await fullItemPage.getByLabel('备注').fill('E2E修改后的备注')
    await fullItemPage.getByRole('button', { name: '保存修改' }).click()
    const editReasonDialog = fullItemPage.getByRole('dialog', { name: '确认保存物料修改' })
    await editReasonDialog.getByLabel('变更说明').fill('E2E验证子物料档案同步')
    await editReasonDialog.getByRole('button', { name: '确认保存', exact: true }).click()
    await expect(fullItemPage.getByText('修改已保存')).toBeVisible()
    await fullItemPage.getByRole('button', { name: '变更记录' }).click()
    await expect(fullItemPage.getByText('E2E验证子物料档案同步')).toBeVisible()
    await expect(fullItemPage.getByText(/名称：.*E2E基础原材料.*E2E基础原材料-已修改/)).toBeVisible()
    await fullItemPage.close()
    await page.bringToFront()
    await expect(quickView).toContainText('E2E基础原材料-已修改')
    await expect(quickView).toContainText('E2E-MAT-02')
    await quickView.getByRole('button', { name: '关闭物料快速查看' }).click()
    await expect(page.getByRole('heading', { name: '01.9902.01', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'BOM 编辑', exact: true })).toHaveClass(/active/)
    await page.getByRole('button', { name: '变更记录' }).click()
    const parentHistory = page.getByTestId('item-history-table')
    const descendantHistoryRow = parentHistory.getByRole('row', { name: /E2E验证子物料档案同步/ })
    await expect(descendantHistoryRow).toContainText('下级组成')
    await expect(descendantHistoryRow).toContainText('01.9901.01')
    await expect(descendantHistoryRow).toContainText('E2E基础原材料-已修改')
    await expect(descendantHistoryRow).toContainText('01.9902.01｜E2E测试半成品 → 01.9901.01｜E2E基础原材料-已修改')
    const addHistoryRow = parentHistory.getByRole('row', { name: /新增 BOM 组成/ }).first()
    await expect(addHistoryRow).toContainText('组件：')
    await expect(addHistoryRow).toContainText('01.9901.01｜E2E基础原材料')
    await page.getByRole('button', { name: 'BOM 编辑' }).click()
    const refreshedDirectRow = page.getByTestId('direct-bom-table').getByRole('row', { name: /01\.9901\.01/ })
    await expect(refreshedDirectRow).toContainText('E2E基础原材料-已修改')
    await expect(refreshedDirectRow.getByLabel('01.9901.01 数量')).toHaveValue('3.750000')

    await page.getByTestId('item-detail').getByRole('button', { name: '技术 BOM', exact: true }).click()
    await expect(page.getByText(/01\.9901\.01/).first()).toBeVisible()
    await page.getByRole('button', { name: '查看详细信息' }).click()
    const technicalDetails = page.getByTestId('technical-detail-table')
    await expect(technicalDetails.locator('th')).toHaveCount(15)
    await expect(technicalDetails.getByRole('cell', { name: '└─ 1级', exact: true })).toBeVisible()
    await expect(technicalDetails).toContainText('E2E基础原材料-已修改')
    await expect(technicalDetails).toContainText('E2E-MAT-02')
    await expect(technicalDetails).toContainText('E2E修改后的备注')
    await technicalDetails.getByRole('button', { name: '快速查看 01.9901.01', exact: true }).click()
    const technicalQuickView = page.getByRole('dialog', { name: '快速查看物料 01.9901.01' })
    await expect(technicalQuickView).toContainText('E2E-MAT-02')
    await technicalQuickView.getByRole('button', { name: '关闭物料快速查看' }).click()
    await expect(technicalDetails).toBeVisible()
    const technicalDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: '导出技术 BOM Excel' }).click()
    expect((await technicalDownload).suggestedFilename()).toBe('01.9902.01-E2E测试半成品-技术BOM.xlsx')
    await page.getByTestId('item-detail').getByRole('button', { name: '生产 BOM', exact: true }).click()
    await expect(page.getByRole('cell', { name: '3.75' })).toBeVisible()
    await page.getByRole('button', { name: '查看详细信息' }).click()
    const productionDetails = page.getByTestId('production-detail-table')
    await expect(productionDetails.locator('th')).toHaveCount(14)
    await expect(productionDetails).toContainText('E2E基础原材料-已修改')
    await expect(productionDetails).toContainText('E2E-MAT-02')
    await expect(productionDetails).toContainText('E2E修改后的备注')
    const productionDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: '导出生产 BOM Excel' }).click()
    expect((await productionDownload).suggestedFilename()).toBe('01.9902.01-E2E测试半成品-生产BOM.xlsx')
    await page.getByRole('button', { name: 'BOM 编辑' }).click()
    page.once('dialog', dialog => dialog.accept())
    await page.getByTestId('direct-bom-table').getByRole('row', { name: /01\.9901\.01/ }).getByRole('button', { name: '移除' }).click()
    await expect(page.getByText(/BOM 组成已移除.*已刷新/)).toBeVisible()
    await page.getByRole('button', { name: '变更记录' }).click()
    const removeHistoryRow = page.getByTestId('item-history-table').getByRole('row', { name: /移除 BOM 组成/ })
    await expect(removeHistoryRow).toContainText('移除组成')
    await expect(removeHistoryRow).toContainText('01.9901.01｜E2E基础原材料-已修改')
    await page.getByRole('button', { name: '复制新版本' }).click()
    await expect(page.getByText(/已创建版本 01\.9902\.02/)).toBeVisible()
    await page.getByRole('row', { name: /01\.9902\.02 E2E测试半成品/ }).getByRole('checkbox').click()
    const batchDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: /批量导出技术 BOM ZIP/ }).click()
    expect((await batchDownload).suggestedFilename()).toContain('批量技术BOM')
    const productionBatchDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: /批量导出生产 BOM ZIP/ }).click()
    expect((await productionBatchDownload).suggestedFilename()).toContain('批量生产BOM')

    await page.getByRole('link', { name: '原材料', exact: true }).click()
    await page.getByTestId('new-item').click()
    await page.getByLabel('系统物料编码').fill('01.9903.01')
    await page.getByLabel('名称', { exact: true }).fill('E2E外协原材料')
    await page.locator('form.modal label').filter({ hasText: /^来源/ }).locator('select').selectOption('outsourced')
    await expect(page.getByText(/外协、自制原材料均允许先作为叶子保存/)).toBeVisible()
    await page.getByText('已检查并确认可能存在的高度相似物料').click()
    await page.getByRole('button', { name: '创建物料' }).click()
    await expect(page.getByText('物料创建成功')).toBeVisible()
    await page.getByLabel('规格型号').fill('E2E-OUT-LEAF-02')
    await page.getByLabel('备注').fill('外协无组成按普通原材料维护')
    await page.getByRole('button', { name: '保存修改' }).click()
    const leafEditReasonDialog = page.getByRole('dialog', { name: '确认保存物料修改' })
    await leafEditReasonDialog.getByLabel('变更说明').fill('E2E验证外协叶子修改')
    await leafEditReasonDialog.getByRole('button', { name: '确认保存', exact: true }).click()
    await expect(page.getByText('修改已保存')).toBeVisible()
    await expect(page.getByLabel('规格型号')).toHaveValue('E2E-OUT-LEAF-02')
    await page.getByTestId('item-detail').getByRole('button', { name: '生产 BOM', exact: true }).click()
    await expect(page.getByTestId('item-detail').getByRole('cell', { name: '01.9903.01' })).toBeVisible()
  })

  test('Excel 预览、所选行提交与结果下载', async ({ page }) => {
    await login(page)
    await page.getByRole('link', { name: '物料导入' }).click()
    await page.getByLabel('选择原材料Excel').setInputFiles('../runtime/e2e-material-import.xlsx')
    await page.getByRole('button', { name: '预览导入' }).click()
    await expect(page.getByText('E2E导入专用垫片')).toBeVisible()
    const reportDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: '下载结果' }).click()
    expect((await reportDownload).suggestedFilename()).toContain('导入批次')
    await page.getByRole('button', { name: /一次性提交 1 行/ }).click()
    await expect(page.getByText('整批成功创建 1 条物料')).toBeVisible()
  })

  test('批量维护、矩阵比较、替代组与编码规则', async ({ page }) => {
    await login(page)
    await page.getByRole('link', { name: '批量维护' }).click()
    await page.getByLabel('业务操作').selectOption('add')
    await chooseAutocomplete(page, '要新增的子物料', '01.9901.01')
    await expect(page.getByText(/层级合法的父项/)).toBeVisible()
    await page.getByLabel('父项层级').selectOption('semi_finished')
    await chooseAutocomplete(page, '添加父项', '01.9902.01')
    await page.getByRole('button', { name: '加入父项' }).click()
    await page.getByRole('button', { name: '预览实际变化' }).click()
    await expect(page.getByText('预计处理 1 条直接 BOM 组成')).toBeVisible()
    await expect(page.getByRole('cell', { name: /已有组成，数量累加|新增组成/ })).toBeVisible()
    page.once('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: '确认执行并记录变更' }).click()
    await expect(page.getByText('批量操作完成')).toBeVisible()

    await page.getByLabel('业务操作').selectOption('delete')
    await page.getByLabel('待删除子物料层级').selectOption('material')
    await chooseAutocomplete(page, '待删除子物料', '01.9901.01')
    await expect(page.getByText(/直接包含该物料的父项/)).toBeVisible()
    const parentBox = page.locator('label.item-combobox').filter({ hasText: '添加父项' })
    await parentBox.locator('input').fill('01.9902')
    const parentOptions = parentBox.getByRole('option')
    await expect(parentOptions.filter({ hasText: '01.9902.01' })).toBeVisible()

    await page.getByRole('link', { name: 'BOM 比较' }).click()
    await expect(page.getByRole('button', { name: '筛选', exact: true })).toHaveCount(0)
    const compareSearch = page.waitForResponse(response => response.ok() && response.url().includes('/api/items?') && response.url().includes('q=00.999'))
    await page.getByLabel('编码/名称/规格').fill('00.999')
    await compareSearch
    const compareRows = page.locator('section.card tbody tr')
    await expect.poll(() => compareRows.count()).toBeGreaterThan(1)
    await compareRows.nth(0).click()
    await compareRows.nth(1).click()
    await page.getByRole('button', { name: '开始比较' }).click()
    await expect(page.getByRole('button', { name: '导出 Excel' })).toBeVisible()
    const compareDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: '导出 Excel' }).click()
    expect((await compareDownload).suggestedFilename()).toContain('BOM差异')

    await page.getByRole('link', { name: '选配替代' }).click()
    await expect(page.getByRole('heading', {name:'选配关系总览'})).toBeVisible()
    await expect(page.getByRole('button', {name:'创建替代组'})).toHaveCount(0)
    await page.getByRole('button', {name:'查看／编辑所在 BOM'}).first().click()
    await expect(page.getByRole('dialog', {name:'路径选配配置'})).toBeVisible()
    await page.getByRole('dialog', {name:'路径选配配置'}).getByRole('button', {name:'取消',exact:true}).click()

    await page.getByRole('link', { name: '编码规则' }).click()
    await page.getByLabel('大类').fill('E2E大类')
    await page.getByLabel('小类').fill('E2E小类')
    await page.getByLabel('材料属性').fill('E2E属性')
    await page.getByLabel('编码前缀').fill('98.8')
    await page.getByLabel('编码样式').fill('98.8XXX.01')
    await page.getByRole('button', { name: '创建规则' }).click()
    await expect(page.getByText('编码规则已创建')).toBeVisible()
    await page.getByRole('button', { name: '试算编码' }).last().click()
    await expect(page.getByText(/推荐编码/)).toBeVisible()
    await page.getByLabel('选择编码规则 Excel').setInputFiles('../data/templates/新增原材料编码登记表(模版).xlsx')
    await page.getByRole('button', { name: '预览规则差异' }).click()
    await expect(page.getByText(/共 81 条/)).toBeVisible()
    page.once('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: '确认按类型替换' }).click()
    await expect(page.getByText(/已替换 81 条规则，其他物料类型规则已保留/)).toBeVisible()
    page.once('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: '恢复' }).first().click()
    await expect(page.getByText(/已恢复规则快照/)).toBeVisible()
  })

  test('完整演示 BOM 树、跨物料导航、中文状态与变更记录', async ({ page }) => {
    test.setTimeout(120_000)
    await login(page)
    await page.getByRole('link', { name: '整机', exact: true }).click()
    await chooseAutocomplete(page, '搜索物料', '00.999.01')
    const machineRow = page.getByRole('row', { name: /00\.999\.01 演示-V1完整水质分析仪/ })
    await expect(machineRow).toContainText('试制')
    await expect(page.getByRole('heading', { name: '完整层级结构' })).toBeVisible()
    await expect(page.getByRole('button', { name: '快速查看 03.999.01', exact: true }).first()).toBeVisible()
    await page.getByRole('button', { name: 'BOM 编辑' }).click()
    await expect(page.getByRole('heading', { name: '完整层级结构' })).toBeVisible()
    await page.getByTestId('direct-bom-table').getByRole('button', { name: '快速查看 03.999.01', exact: true }).first().click()
    let quickView = page.getByRole('dialog', { name: '快速查看物料 03.999.01' })
    await expect(quickView).toContainText('演示-水质分析单元')
    await expect(quickView).toContainText('DEMO-UNIT-ANALYSIS-STD')
    await quickView.getByRole('button', { name: '快速查看 05.999.01', exact: true }).first().click()
    await expect(page.getByRole('dialog', { name: '快速查看物料 03.999.01' })).toHaveCount(0)
    quickView = page.getByRole('dialog', { name: '快速查看物料 05.999.01' })
    await expect(quickView).toBeVisible()
    await expect(quickView).toContainText('演示-水质采集半成品')
    await expect(quickView.getByRole('button', { name: '快速查看 90.9003.01', exact: true }).first()).toBeVisible()
    await quickView.getByRole('button', { name: '关闭物料快速查看' }).click()
    await expect(page.getByRole('heading', { name: '00.999.01', exact: true })).toBeVisible()
    await expectSelectedListRow(page, '00.999.01')

    await page.getByRole('button', { name: 'BOM 编辑' }).click()
    await expect(page.getByRole('button', { name: '展开' }).first()).toBeVisible()
    await page.getByRole('button', { name: '全部展开' }).click()
    await expect(page.getByRole('button', { name: '快速查看 05.999.01', exact: true }).first()).toBeVisible()
    await expect(page.getByRole('button', { name: '快速查看 90.9003.01', exact: true }).first()).toBeVisible()
    await page.getByRole('button', { name: '快速查看 05.999.01', exact: true }).first().click()
    quickView = page.getByRole('dialog', { name: '快速查看物料 05.999.01' })
    await expect(quickView).toContainText('演示-水质采集半成品')
    await expect(quickView.getByText('90.9003.01')).toBeVisible()
    await quickView.getByRole('button', { name: '关闭物料快速查看' }).click()
    await expect(page.getByRole('heading', { name: '00.999.01' })).toBeVisible()
    await expectSelectedListRow(page, '00.999.01')

    await page.getByRole('button', { name: '技术 BOM', exact: true }).click()
    await page.getByTestId('item-detail').getByRole('button', { name: '快速查看 03.999.01', exact: true }).first().click()
    quickView = page.getByRole('dialog', { name: '快速查看物料 03.999.01' })
    await expect(quickView).toContainText('演示-水质分析单元')
    await quickView.getByRole('button', { name: '关闭物料快速查看' }).click()
    await expect(page.getByRole('button', { name: '技术 BOM', exact: true })).toHaveClass(/active/)
    await expectSelectedListRow(page, '00.999.01')

    await page.getByRole('button', { name: '生产 BOM', exact: true }).click()
    await page.getByTestId('item-detail').getByRole('button', { name: '快速查看 90.9001.01', exact: true }).first().click()
    quickView = page.getByRole('dialog', { name: '快速查看物料 90.9001.01' })
    await expect(quickView).toContainText('演示-M4不锈钢螺钉')
    await expect(quickView.getByRole('heading', { name: '直接组成' })).toHaveCount(0)
    await quickView.getByRole('button', { name: '关闭物料快速查看' }).click()
    await page.getByRole('button', { name: '查看详细信息' }).click()
    await page.getByTestId('production-detail-table').getByRole('button', { name: '快速查看 90.9001.01', exact: true }).first().click()
    quickView = page.getByRole('dialog', { name: '快速查看物料 90.9001.01' })
    await expect(quickView).toContainText('M4×12，304不锈钢')
    await quickView.getByRole('button', { name: '关闭物料快速查看' }).click()
    await expect(page.getByRole('button', { name: '生产 BOM', exact: true })).toHaveClass(/active/)
    await expectSelectedListRow(page, '00.999.01')

    await page.getByRole('button', { name: '变更记录' }).click()
    await expect(page.getByText('演示整机说明变更记录')).toBeVisible()
    await expect(page.getByText('创建虚拟演示数据集').first()).toBeVisible()
    await page.getByTestId('item-history-table').getByRole('button', { name: '快速查看 00.999.01', exact: true }).first().click()
    quickView = page.getByRole('dialog', { name: '快速查看物料 00.999.01' })
    await expect(quickView).toContainText('演示-V1完整水质分析仪')
    await quickView.getByRole('button', { name: '关闭物料快速查看' }).click()
    await expect(page.getByRole('button', { name: '变更记录', exact: true })).toHaveClass(/active/)

    await page.getByRole('link', { name: '单元', exact: true }).click()
    await chooseAutocomplete(page, '搜索物料', '03.999.01')
    await expect(page.getByRole('heading', { name: '完整层级结构' })).toBeVisible()
    await expect(page.getByRole('button', { name: '快速查看 05.999.01', exact: true }).first()).toBeVisible()
    await page.getByRole('button', { name: '变更记录' }).click()
    await expect(page.getByText('演示单元名称变更记录')).toBeVisible()
    await expect(page.getByText(/名称：.*初版.*演示-水质分析单元/)).toBeVisible()

    await page.getByRole('link', { name: '半成品', exact: true }).click()
    await chooseAutocomplete(page, '搜索物料', '05.999.01')
    await expect(page.getByRole('heading', { name: '完整层级结构' })).toBeVisible()
    await expect(page.getByRole('button', { name: '快速查看 90.9003.01', exact: true }).first()).toBeVisible()
    await page.getByRole('button', { name: '反向追溯' }).click()
    await expect(page.getByText('路径按“上级父项 → … → 当前物料”显示')).toBeVisible()
    await expect(page.getByText('直接引用').first()).toBeVisible()
    const referencesTable = page.getByTestId('item-detail')
    const relationTable = page.getByTestId('references-table')
    await page.getByLabel('引用关系筛选').selectOption('direct')
    await expect(relationTable.getByText('直接引用', { exact: true }).first()).toBeVisible()
    await expect(relationTable.getByText('间接引用', { exact: true })).toHaveCount(0)
    await page.getByLabel('引用关系筛选').selectOption('indirect')
    await expect(relationTable.getByText('间接引用', { exact: true }).first()).toBeVisible()
    await expect(relationTable.getByText('直接引用', { exact: true })).toHaveCount(0)
    await page.getByLabel('引用关系筛选').selectOption('all')
    await expect(referencesTable.getByRole('button', { name: '快速查看 03.999.01', exact: true }).first()).toBeVisible()
    await expect(referencesTable.getByRole('button', { name: '快速查看 05.999.01', exact: true }).first()).toBeVisible()
    await referencesTable.getByRole('button', { name: '快速查看 03.999.01', exact: true }).first().click()
    quickView = page.getByRole('dialog', { name: '快速查看物料 03.999.01' })
    await expect(quickView).toContainText('演示-水质分析单元')
    await quickView.getByRole('button', { name: '关闭物料快速查看' }).click()
    await referencesTable.getByRole('button', { name: '快速查看 05.999.01', exact: true }).first().click()
    quickView = page.getByRole('dialog', { name: '快速查看物料 05.999.01' })
    await expect(quickView).toContainText('演示-水质采集半成品')
    await quickView.getByRole('button', { name: '关闭物料快速查看' }).click()
    await expect(page.getByRole('heading', { name: '05.999.01', exact: true })).toBeVisible()
    await expectSelectedListRow(page, '05.999.01')
  })

  test('半成品、单元和整机新建支持同类型复制与编码实时校验', async ({ page }) => {
    await login(page)
    const cases = [
      { label: '半成品', source: '05.999.01', body: '05.999.', large: '半成品', small: '模块和组件（CBB）', prefix: '05.', combination: true },
      { label: '单元', source: '03.999.01', body: '03.999.', large: '单元', small: '分析单元或电气机柜', prefix: '03.' },
      { label: '整机', source: '00.999.01', body: '00.999.', large: '整机', small: '包装后的成品机', prefix: '00.' },
    ]
    for (const row of cases) {
      await page.getByRole('link', { name: row.label, exact: true }).click()
      await page.getByTestId('new-item').click()
      const modal = page.locator('.modal')
      await expect(modal.getByRole('heading', { name: `复制已有${row.label}（可选）` })).toBeVisible()
      await chooseAutocomplete(page, `选择要复制的${row.label}`, row.source)
      await modal.getByRole('button', { name: '复制并自动填充' }).click()
      await expect(modal.getByLabel('大类')).toHaveValue(row.large)
      await expect(modal.getByLabel('小类')).toHaveValue(row.small)
      await expect(modal.getByTestId('code-rule-prefix')).toHaveText(row.prefix)
      const nextCode = (await modal.getByTestId('full-material-code').textContent() || '').trim()
      expect(nextCode).toMatch(new RegExp(`^${row.body.replaceAll('.', '\\.')}\\d+$`))
      expect(nextCode).not.toBe(row.source)
      await expect(modal.getByText(/复制的 BOM 组成（\d+）/)).toBeVisible()
      if (row.combination) {
        await expect(modal.getByRole('heading', { name: '下级组成（可选）' })).toBeVisible()
        await chooseAutocomplete(page, '选择下级组成', '05.999.02')
        await modal.getByRole('button', { name: '加入组成' }).click()
        await expect(modal.getByText(/半成品 05\.999\.02 演示-流路驱动半成品/)).toBeVisible()
      }
      await expect(modal.getByText('系统物料编码可用')).toBeVisible()
      await expect(modal.getByRole('button', { name: '创建物料' })).toBeEnabled()
      await modal.getByRole('button', { name: '创建物料' }).click()
      await expect(page.getByText('物料创建成功')).toBeVisible()
      if (row.combination) {
        const heading = page.getByRole('heading', { name: new RegExp(nextCode.replaceAll('.', '\\.')) })
        await expect(heading).toBeVisible()
        await expect(heading.locator('.tag')).toHaveText('组合半成品')
      } else {
        await expect(page.getByRole('heading', { name: nextCode, exact: true })).toBeVisible()
      }
    }
  })

  test('V1.1 选配占比、统一展开开关、BOM 替换与组合半成品', async ({ page }) => {
    test.setTimeout(120_000)
    await login(page)
    await page.getByRole('link', { name: '整机', exact: true }).click()
    await chooseAutocomplete(page, '搜索物料', '00.999.01')
    await page.getByRole('button', { name: '技术 BOM', exact: true }).click()
    await page.getByLabel('显示选配替代').check()
    await expect(page.getByText('备用选配', { exact: true }).first()).toBeVisible()
    await page.getByRole('button', { name: '查看详细信息' }).click()
    await expect(page.getByTestId('technical-detail-table').locator('th')).toHaveCount(15)
    await expect(page.getByTestId('technical-detail-table')).toContainText('市场占比')
    await page.getByRole('button', { name: '生产 BOM', exact: true }).click()
    await page.getByLabel('显示选配替代').check()
    await expect(page.getByText('备用选配（不计入汇总）', { exact: true }).first()).toBeVisible()

    // Share redistribution and confirmation are exercised in bom-v1_2.spec.ts.
    await page.getByRole('link', { name: '半成品', exact: true }).click()
    await chooseAutocomplete(page, '搜索物料', '05.999.04')
    await page.getByRole('button', { name: 'BOM 编辑' }).click()
    const powerRow = page.getByTestId('direct-bom-table').getByRole('row', { name: /90\.9011\.01/ })
    await powerRow.getByRole('button', { name: '替换' }).click()
    await chooseAutocomplete(page, '替换目标物料', '90.9012.01')
    await page.getByRole('dialog', { name: /替换 BOM 组成/ }).getByLabel('变更说明').fill('E2E验证V1.1行级替换')
    await page.getByRole('button', { name: '确认替换' }).click()
    await expect(page.getByText(/已将 90\.9011\.01.*替换为 90\.9012\.01/)).toBeVisible()
    await expect(page.getByTestId('direct-bom-table').getByRole('button', { name: '快速查看 90.9012.01', exact: true })).toBeVisible()

    await expect(page.getByRole('heading', { name: /05\.999\.04/ }).locator('.tag')).toHaveText('组合半成品')
    const combinationResponse = page.waitForResponse(response => {
      const url = new URL(response.url())
      return response.ok() && url.pathname === '/api/items' && url.searchParams.get('semi_kind') === 'combination'
    })
    await page.getByLabel('半成品分类筛选').selectOption('combination')
    await combinationResponse
    await expect(page.getByTestId('item-list-table').getByRole('row', { name: /05\.999\.04/ })).toContainText('组合半成品')
  })

  test('V1.1.1 未正式 99 编号、关键器件码与新建正式物料封存追溯', async ({ page }) => {
    test.setTimeout(120_000)
    await login(page)
    await page.getByRole('link', { name: '原材料', exact: true }).click()
    await page.getByTestId('new-item').click()
    const createModal = page.locator('.modal')
    await createModal.getByLabel('导入状态').selectOption({ label: '未正式导入' })
    await expect(createModal.getByLabel('未正式原材料预计编号')).toHaveValue(/^99\.\d{4}\.\d$/)
    const pendingCode = await createModal.getByLabel('未正式原材料预计编号').inputValue()
    await expect(createModal.getByText('预计编号，不提前占号')).toBeVisible()
    await createModal.getByLabel('名称', { exact: true }).fill('E2E待转正式关键器件')
    await createModal.getByLabel('规格型号').fill('E2E-V111-TEMP')
    await createModal.getByLabel('关键器件码').fill('f33.b')
    await expect(createModal.getByText(/该关键器件码已关联 \d+ 条物料，可继续保存/)).toBeVisible()
    await createModal.getByText('已检查并确认可能存在的高度相似物料').click()
    await createModal.getByRole('button', { name: '创建物料' }).click()
    await expect(page.getByText(`物料创建成功，最终编号：${pendingCode}`)).toBeVisible()
    await expect(page.getByRole('heading', { name: pendingCode, exact: true })).toBeVisible()
    await expect(page.getByRole('textbox', { name: '正式导入状态', exact: true })).toHaveValue('待转正式')
    await expect(page.getByLabel('关键器件码')).toHaveValue('F33.B')

    await page.getByRole('button', { name: '转为正式导入' }).click()
    const promoteModal = page.locator('.modal')
    await expect(promoteModal.getByText(`来源 ${pendingCode} 将永久封存`, { exact: false })).toBeVisible()
    await promoteModal.getByLabel('大类').selectOption({ index: 1 })
    await promoteModal.getByLabel('小类').selectOption({ index: 1 })
    await promoteModal.getByLabel('编码规则').selectOption({ index: 1 })
    const officialCode = await promoteModal.getByLabel('正式系统物料编码').inputValue()
    expect(officialCode).not.toBe('')
    expect(officialCode.startsWith('99.')).toBe(false)
    await expect(promoteModal.getByText('系统物料编码可用')).toBeVisible()
    await promoteModal.getByText('已检查并确认可能存在的高度相似正式物料').click()
    await promoteModal.getByLabel('变更说明').fill('E2E验证 V1.1.1 转正式封存事务')
    await promoteModal.getByRole('button', { name: '创建正式物料并封存来源' }).click()
    await expect(page.getByText(new RegExp(`已创建正式物料 ${officialCode.replaceAll('.', '\\.')}；来源未正式物料已封存`))).toBeVisible()
    await expect(page.getByRole('heading', { name: officialCode, exact: true })).toBeVisible()
    await expect(page.getByText('来源未正式物料：')).toBeVisible()
    await expect(page.getByRole('button', { name: pendingCode, exact: true })).toBeVisible()

    const archivedResponse = page.waitForResponse(response => {
      const url = new URL(response.url())
      return response.ok() && url.pathname === '/api/items' && url.searchParams.get('unofficial_status') === 'archived'
    })
    await page.getByLabel('正式导入状态筛选').selectOption('archived')
    await archivedResponse
    await chooseAutocomplete(page, '搜索物料', pendingCode)
    await expect(page.getByText('封存来源，仅供历史参考。档案和 BOM 可以查看、导出，但不能修改、删除、恢复或再次转正式。')).toBeVisible()
    await expect(page.getByText(`已转为正式物料：`)).toBeVisible()
    await expect(page.getByRole('button', { name: '保存修改' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: '转为正式导入' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: '删除', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'BOM 编辑' }).click()
    await expect(page.getByRole('button', { name: '添加组成' })).toHaveCount(0)
  })

  test('账户权限、不可变审计导出与数据库备份', async ({ page }) => {
    await login(page)
    await page.getByRole('link', { name: '账户管理' }).click()
    await page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'guest', exact: true }) }).getByRole('button', { name: '编辑 / 重置密码' }).click()
    await page.getByLabel('新密码').fill('viewer123')
    await page.getByLabel('显示名称').fill('E2E查看者')
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await expect(page.getByText(/账户已更新/)).toBeVisible()

    await page.getByRole('link', { name: '变更日志' }).click()
    const auditDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: '导出日志' }).click()
    expect((await auditDownload).suggestedFilename()).toContain('变更日志')
    await page.getByRole('button', { name: '创建数据库备份' }).click()
    await expect(page.getByText(/备份已创建/)).toBeVisible()

    await page.getByRole('button', { name: '退出登录' }).click()
    await page.getByLabel('用户名').fill('guest')
    await page.getByLabel('密码').fill('viewer123')
    await page.getByRole('button', { name: '登录', exact: true }).click()
    await page.getByRole('link', { name: '原材料', exact: true }).click()
    await expect(page.getByTestId('new-item')).toHaveCount(0)
    await expect(page.getByRole('link', { name: '账户管理' })).toHaveCount(0)
    await page.goto('/users')
    await expect(page.getByRole('heading', { name: '工作台' })).toBeVisible()
  })
})
