<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { api, session, canWriteBusiness } from '../api'
const rows=ref<any[]>([]);const error=ref('');const message=ref('');const recommendation=ref('')
const importFile=ref<File|null>(null);const importPreview=ref<any>(null);const snapshots=ref<any[]>([])
const editingRule=ref<any|null>(null);const ruleEdit=reactive({material_attribute:'',description:'',reason:''})
const form=reactive({item_type:'material',large_category:'',small_category:'',material_attribute:'',prefix:'',pattern:'',description:'',active:true,sort_order:0})
const largeOptions=computed(()=>[...new Set(rows.value.filter(row=>row.item_type===form.item_type).map(row=>row.large_category).filter(Boolean))])
const smallOptions=computed(()=>[...new Set(rows.value.filter(row=>row.item_type===form.item_type&&(!form.large_category||row.large_category===form.large_category)).map(row=>row.small_category).filter(Boolean))])
const attributeOptions=computed(()=>[...new Set(rows.value.filter(row=>row.item_type===form.item_type&&(!form.large_category||row.large_category===form.large_category)&&(!form.small_category||row.small_category===form.small_category)).map(row=>row.material_attribute).filter(Boolean))])
async function load(){rows.value=await api('/code-rules');if(canWriteBusiness())snapshots.value=await api('/code-rule-snapshots')}
async function create(){try{await api('/code-rules',{method:'POST',body:JSON.stringify(form)});message.value='编码规则已创建';Object.assign(form,{large_category:'',small_category:'',material_attribute:'',prefix:'',pattern:'',description:'',sort_order:0});await load()}catch(event){error.value=(event as Error).message}}
async function recommend(id:number){const result=await api<any>(`/code-rules/${id}/recommend`);recommendation.value=result.recommended_code}
function chooseFile(event:Event){importFile.value=(event.target as HTMLInputElement).files?.[0]||null}
async function previewImport(){if(!importFile.value)return;const data=new FormData();data.append('file',importFile.value);try{importPreview.value=await api('/code-rule-imports/preview',{method:'POST',body:data})}catch(event){error.value=(event as Error).message}}
async function applyImport(){if(!importPreview.value||!confirm('确认替换导入文件涉及的物料类型规则？其他类型规则会保留。'))return;try{const result=await api<any>('/code-rule-imports/apply',{method:'POST',body:JSON.stringify({rules:importPreview.value.rules,reason:'确认按物料类型覆盖编码规则'})});message.value=`已替换 ${result.rules} 条规则，其他物料类型规则已保留，旧规则快照 #${result.snapshot_id}`;importPreview.value=null;await load()}catch(event){error.value=(event as Error).message}}
async function restore(snapshot:any){if(!confirm(`确认恢复快照 #${snapshot.id}？`))return;try{await api(`/code-rule-snapshots/${snapshot.id}/restore?reason=${encodeURIComponent('界面恢复编码规则')}`,{method:'POST'});message.value=`已恢复规则快照 #${snapshot.id}`;await load()}catch(event){error.value=(event as Error).message}}
function startRuleEdit(row:any){editingRule.value=row;Object.assign(ruleEdit,{material_attribute:row.material_attribute||'',description:row.description||'',reason:''});error.value='';message.value=''}
async function saveRuleEdit(){if(!editingRule.value||!ruleEdit.reason.trim())return;try{await api(`/code-rules/${editingRule.value.id}`,{method:'PATCH',body:JSON.stringify(ruleEdit)});editingRule.value=null;message.value='编码规则可编辑信息已保存，变更说明已记录';await load()}catch(event){error.value=(event as Error).message}}
onMounted(load)
</script>
<template><header class="page-head"><div><h1>编码规则</h1><p class="subtitle">数据库是运行期规则权威来源；新建物料时按分类逐步引导</p></div></header><div v-if="error" class="notice error">{{error}}</div><div v-if="message" class="notice">{{message}}</div><div v-if="recommendation" class="notice">推荐编码：<strong>{{recommendation}}</strong></div>
<div class="grid" :class="{'grid-2':canWriteBusiness()}"><section v-if="canWriteBusiness()" class="card"><h2>新增规则</h2><p class="subtitle">大类、小类和材料属性均可从已有值中选择，也可直接输入新值；小类候选会随大类联动。</p><form class="form-grid" @submit.prevent="create"><label>物料类型<select v-model="form.item_type" @change="form.large_category='';form.small_category='';form.material_attribute='' "><option value="material">原材料</option><option value="semi_finished">半成品</option><option value="unit">单元</option><option value="machine">整机</option></select></label><label>大类<input v-model="form.large_category" list="large-category-options" placeholder="选择已有或输入新大类"/><datalist id="large-category-options"><option v-for="value in largeOptions" :key="value" :value="value"/></datalist></label><label>小类<input v-model="form.small_category" list="small-category-options" placeholder="选择已有或输入新小类"/><datalist id="small-category-options"><option v-for="value in smallOptions" :key="value" :value="value"/></datalist></label><label>材料属性<input v-model="form.material_attribute" list="attribute-options" placeholder="选择已有或输入新属性"/><datalist id="attribute-options"><option v-for="value in attributeOptions" :key="value" :value="value"/></datalist></label><label>编码前缀<input v-model="form.prefix" required placeholder="10.1"/></label><label>编码样式<input v-model="form.pattern" required placeholder="10.1XXX.01"/></label><label class="span-2">说明<input v-model="form.description"/></label><div class="actions span-2"><button class="btn">创建规则</button></div></form><hr style="border:0;border-top:1px solid #e2e8f0;margin:22px 0"/><h2>Excel 受控覆盖</h2><p class="subtitle">导入只替换文件中涉及的物料类型；例如导入原材料模板不会删除半成品、单元和整机规则。</p><label>选择编码规则 Excel<input type="file" accept=".xlsx,.xlsm" @change="chooseFile"/></label><div class="actions"><button class="btn secondary" :disabled="!importFile" @click="previewImport">预览规则差异</button></div><div v-if="importPreview" class="notice">共 {{importPreview.counts.rules}} 条；新增 {{importPreview.counts.added}}，修改 {{importPreview.counts.changed}}，删除 {{importPreview.counts.removed}}。<button class="btn danger small" @click="applyImport">确认按类型替换</button></div><h3>最近快照</h3><p v-for="snapshot in snapshots" :key="snapshot.id">#{{snapshot.id}}｜{{snapshot.rules}} 条｜{{snapshot.reason}} <button class="btn secondary small" @click="restore(snapshot)">恢复</button></p></section>
<section class="card"><h2>当前规则（{{rows.length}}）</h2><p class="subtitle">已有规则仅允许普通编辑“材料属性”和“说明”；分类、前缀和样式须通过 Excel 受控覆盖维护。</p><div class="table-wrap"><table><thead><tr><th>分类</th><th>属性</th><th>前缀/样式</th><th>说明</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{row.large_category}}<br/><small>{{row.small_category}}</small></td><td>{{row.material_attribute||'—'}}</td><td>{{row.prefix}}<br/><small>{{row.pattern}}</small></td><td>{{row.description||'—'}}</td><td><button class="btn secondary small" @click="recommend(row.id)">试算编码</button> <button v-if="canWriteBusiness()" class="btn secondary small" @click="startRuleEdit(row)">编辑属性/说明</button></td></tr></tbody></table></div></section></div>
<div v-if="editingRule" class="modal-mask"><form class="modal" @submit.prevent="saveRuleEdit"><div class="modal-head"><h2>编辑编码规则</h2><button type="button" aria-label="关闭" @click="editingRule=null">×</button></div><div class="notice">规则：{{editingRule.large_category}}｜{{editingRule.small_category}}｜{{editingRule.prefix}}｜{{editingRule.pattern}}<br/>分类、前缀和编码样式在此不可修改。</div><label>材料属性<input v-model="ruleEdit.material_attribute" list="attribute-options"/></label><label>说明<textarea v-model="ruleEdit.description" rows="3"/></label><label>变更说明<input v-model="ruleEdit.reason" required placeholder="说明本次修改原因，将写入不可变审计历史"/></label><div class="actions"><button type="button" class="btn secondary" @click="editingRule=null">取消</button><button class="btn" :disabled="!ruleEdit.reason.trim()">保存修改</button></div></form></div></template>
