<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api, session, type User } from '../api'
import { roleLabels } from '../labels'
const rows=ref<User[]>([]);const error=ref('');const message=ref('');const form=reactive({username:'',password:'',display_name:'',department:'',role:'viewer',active:true})
async function load(){if(session.user?.role==='admin')rows.value=await api('/users')}
async function create(){try{await api('/users',{method:'POST',body:JSON.stringify(form)});message.value='账户创建成功';Object.assign(form,{username:'',password:'',display_name:'',department:'',role:'viewer',active:true});await load()}catch(event){error.value=(event as Error).message}}
async function toggle(user:User){try{await api(`/users/${user.id}`,{method:'PATCH',body:JSON.stringify({active:!user.active})});await load()}catch(event){error.value=(event as Error).message}}
onMounted(load)
</script>
<template><header class="page-head"><div><h1>账户管理</h1><p class="subtitle">固定管理员、维护员、查看者三种基础角色</p></div></header><div v-if="session.user?.role!=='admin'" class="notice error">仅管理员可以访问账户管理。</div><template v-else><div v-if="error" class="notice error">{{error}}</div><div v-if="message" class="notice">{{message}}</div><div class="grid grid-2"><section class="card"><h2>创建账户</h2><form class="form-grid" @submit.prevent="create"><label>用户名<input v-model="form.username" minlength="3" required/></label><label>初始密码<input v-model="form.password" type="password" minlength="6" required/></label><label>显示名称<input v-model="form.display_name" required/></label><label>部门<input v-model="form.department"/></label><label>角色<select v-model="form.role"><option value="viewer">查看者</option><option value="maintainer">维护员</option><option value="admin">管理员</option></select></label><div class="actions span-2"><button class="btn">创建账户</button></div></form></section><section class="card"><h2>账户列表</h2><table><thead><tr><th>用户名</th><th>姓名</th><th>角色</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="user in rows" :key="user.id"><td>{{user.username}}</td><td>{{user.display_name}}</td><td>{{roleLabels[user.role]||user.role}}</td><td><span class="tag" :class="{red:!user.active}">{{user.active?'启用':'停用'}}</span></td><td><button class="btn secondary small" :disabled="user.id===session.user?.id" @click="toggle(user)">{{user.active?'停用':'启用'}}</button></td></tr></tbody></table></section></div></template></template>
